CREATE DATABASE payment_db;

USE payment_db;
DROP TABLE IF EXISTS TRANSTION;
 DROP TABLE IF EXISTS BILL;

 CREATE TABLE BILL(
ID INT NOT NULL UNIQUE ,
NAME VARCHAR(50) NOT NULL,
AMOUNT  DECIMAL(10,2) NOT NULL,
PRIMARY KEY(ID)
);

CREATE TABLE TRANSTION(
ID INT NOT  NULL UNIQUE auto_increment,
PRIMARY KEY(ID),
fk_bill_id INT NOT NULL,
FOREIGN KEY (fk_bill_id) REFERENCES BILL(ID)
);

-- Insert bills
INSERT INTO BILL (ID, NAME, AMOUNT) VALUES
(1, 'Electricity Bill', 1500.50),
(2, 'Water Bill', 500.75),
(3, 'Internet Bill', 1200.00),
(4, 'Gas Bill', 800.25);





